ALTER TABLE settings
ADD COLUMN IF NOT EXISTS show_delivery BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS show_pickup BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS show_payment BOOLEAN DEFAULT true;
